#!/usr/bin/env bash
# Regenerates FULL-SPEC.md from the numbered files in reading order. Never edit FULL-SPEC.md by hand.
set -euo pipefail
cd "$(dirname "$0")"
files=(12-constitution.md README.md 01-product-and-scope.md 02-domain-model.md 03-scoring-and-uncertainty.md
       04-agent-protocol.md 05-identity-reputation-and-security.md 06-api-and-ui.md
       07-poc-roadmap-and-acceptance.md 08-seeded-example.md 09-future-directions.md
       10-agent-handoff.md 11-rails-architecture.md 13-constitutional-compliance.md CONSTITUTION-AMENDMENTS.md examples/watchers/README.md)
{
  echo "<!-- GENERATED by build-full-spec.sh — do not edit. Read this OR the numbered files, not both. -->"
  for f in "${files[@]}"; do
    printf '\n---\n\n# FILE: %s\n\n' "$f"
    cat "$f"
  done
} > FULL-SPEC.md
echo "wrote FULL-SPEC.md ($(wc -c < FULL-SPEC.md) bytes)"
